{
  "packages": [
    "apps/*",
    "packages/*"
  ],
  "catalog": {
    "@types/node": "^25.9.3"
  },
  "catalogs": {
    "linting": {
      "oxlint": "^1.70.0",
      "oxlint-tsgolint": "^0.23.0",
      "oxfmt": "^0.55.0"
    },
    "testing": {
      "@vitest/coverage-v8": "^4.1.9",
      "globals": "^17.6.0",
      "vite-tsconfig-paths": "^6.1.1",
      "vitest": "^4.1.9"
    },
    "tooling": {
      "ts-loader": "^9.6.1",
      "ts-node": "^10.9.2",
      "tsconfig-paths": "^4.2.0",
      "typescript": "^6.0.3"
    }
  },
  "onlyBuiltDependencies": [
    "@nestjs/core",
    "@scarf/scarf",
    "@swc/core",
    "esbuild",
    "protobufjs",
    "unrs-resolver"
  ]
}