{
  "packages": [
    "apps/*",
    "packages/*"
  ],
  "catalog": {
    "@types/node": "^25.2.2"
  },
  "catalogs": {
    "linting": {
      "oxlint": "^1.43.0",
      "oxlint-tsgolint": "^0.11.5",
      "oxfmt": "^0.28.0"
    },
    "testing": {
      "@vitest/coverage-v8": "^4.0.18",
      "globals": "^17.3.0",
      "vite-tsconfig-paths": "^6.1.0",
      "vitest": "^4.0.18"
    },
    "tooling": {
      "ts-loader": "^9.5.4",
      "ts-node": "^10.9.2",
      "tsconfig-paths": "^4.2.0",
      "typescript": "^5.9.3"
    }
  },
  "onlyBuiltDependencies": [
    "@nestjs/core",
    "@scarf/scarf",
    "@swc/core",
    "esbuild",
    "protobufjs",
    "unrs-resolver"
  ]
}